### PR TITLE
script: fix message bad order

### PR DESCRIPTION
**Pull request by t-h2o**
# script/dl.sh

first print the message `curl`, and then execute `curl`

### CODE REVIEW

**Review by 0xCAF3D0OD — COMMENTED** [review]
how i'm supposed to execute the program ?

**Comment by t-h2o** [comment]
> how i'm supposed to execute the program ?

Ref: #40 

```bash
sh ./script/dl.sh
```

**Comment by 0xCAF3D0OD** [comment]
> > how i'm supposed to execute the program ?
> 
> Ref: #40
> 
> ```shell
> sh ./script/dl.sh
> ```

nice ok!

**Review by 0xCAF3D0OD — APPROVED** [review]
OK

**Pull request merged**
