### PR TITLE
json parser: object in object

### PR DESCRIPTION
**Pull request by t-h2o**
#  :package: Object in config file

### Example of config file

```json
{

  "foo.com": {
    "port" : 6060,
    "path" : "/path/of/foo.com"
  },

  "bar.org": {
    "port" : 8080,
    "path" : "/path/of/bar.org"
  },

  "php-cgi" : "/path/of/php-cgi"

}
```

### Changes

* tdd: test object in the config file:
  - json object 01
  - json object 00

* improve `config.json`
* json:
  - check last state
  - add `END_OBJECT` as new state
    the curly brace set this state to 1 `}`
    if we arrive at the end of the object,
    the function should return the object
  - inverse state `OBJECT`, it is set to 1 just
    after to meet `{`

### CODE REVIEW

**Review by RobinBurri — DISMISSED** [review]
RAS

**Review by 0xCAF3D0OD — DISMISSED** [review]
RAS

**Review by RobinBurri — APPROVED** [review]
RAS

**Review by 0xCAF3D0OD — APPROVED** [review]
RAS

**Pull request merged**
